### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by huizhenhe-dev** [wxxsw/GSPlayer#14]
1. I use this code on MacOS, and find the following code will always cancel request.

func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive response: URLResponse, completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
        guard
            let mimeType = response.mimeType,
            mimeType.hasPrefix("video/")
            else { completionHandler(.cancel); return }
        
2. I also change some codes for supporting MacOS, can I commit?

**Comment by wxxsw** [comment]
1. I think it is better to change the mimeType of the resource to the correct value.
2. Of course, thank you.

**Comment by visla-huizhenhe** [comment]
When I try to push codes, it reminds me that “fatal: unable to access 'https://github.com/wxxsw/GSPlayer.git/': The requested URL returned error: 403”. Could you please give me an permission for this?

**Comment by wxxsw** [comment]
You should fork the project, submit the code in your own fork project, and then create a Pull request.

**Comment by visla-huizhenhe** [comment]
I have submit the codes, could you please take a look? Thanks

https://github.com/wxxsw/GSPlayer/pull/15

**Comment by visla-huizhenhe** [comment]
Could you give me an example about “change the mimeType of the resource to the correct value"?

**Comment by wxxsw** [comment]
video/mp4
