### ISSUE TITLE
Does not play video and preload other .mp4 format

### ISSUE THREAD

**Issue by sajib-ghoshInnofied** [wxxsw/GSPlayer#17]
Hi,

This is an awesome library but does this library support video other than .mp4 format?

**Comment by wxxsw** [comment]
Hello, currently only supports mp4 cache. Other formats supported by AVPlayer can be played, but there is no cache.

In fact, since I only use MP4 in the project, I can guarantee that the support for the MP4 format is stable and reliable, so this project does not support other formats.

**Comment by sajib-ghoshInnofied** [comment]
Ok understood. That's fine.

Can you please tell me how I can make the player as fullscreen like AVplayer, where there is a property called videoGravity.

Please let me know.

**Comment by wxxsw** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/921863/102737749-3726d280-4383-11eb-815b-5b2f218088fe.png">
Is it what you need?

**Comment by sajib-ghoshInnofied** [comment]
Thanks for the reply. That's awesome. I didn't notice this property.

I want the player to play the video in fullscreen ( full height of the screen), is this even possible? Or, it solely depends on the dimension of the video?

**Comment by wxxsw** [comment]
Sample:

```swift
let videoRatio = video.height / video.width
let screenRatio = screen.height / screen.width

if videoRatio > screenRatio {
	playerView.contentMode = .scaleAspectFit
} else {
	playerView.contentMode = .scaleAspectFill
}
```

**Comment by sajib-ghoshInnofied** [comment]
Thanks a lot!
I will check and let you know.
