### ISSUE TITLE
Preload - Buffer a specific time 

### ISSUE THREAD

**Issue by turtleCombat** [wxxsw/GSPlayer#18]
Hello,

is there any way to do that? For example I have 5 urls and I want buffering all of urls with start a specific timestamp like start buffering at 3 mins and continue buffering with specified byte

thank you

**Comment by wxxsw** [comment]
Is this what you want? You can set the preload byte size.
`VideoPreloadManager.shared.preloadByteCount = 1024 * 1024 // = 1M`

**Comment by bLajen** [comment]
Hi, no, for example, there are 5 videos. I start watching the first video. I preload this video from the 3rd minute, at the same time, I want to preload the other 4 videos from the 3rd minute to open without any delay when the user opens it.  I'm trying to ask that can we give a starting point to preload.

**Comment by turtleCombat** [comment]
Hi, no, for example, there are 5 videos. I start watching the first video. I preload this video from the 3rd minute, at the same time, I want to preload the other 4 videos from the 3rd minute to open without any delay when the user opens it. I'm trying to ask that can we give a starting point to preload.

**Comment by wxxsw** [comment]
Do you mean that you want the preload to start at the specified time of the video?

**Comment by turtleCombat** [comment]
Yes I am trying to say that

**Comment by wxxsw** [comment]
Maybe changing `from` can work, but I don't have time to test it. If you want, you can modify it and try it.
https://github.com/wxxsw/GSPlayer/blob/d65997d471879b1c03822c306b95acf53659dd6c/GSPlayer/Classes/Loader/VideoPreloadManager.swift#L49

**Comment by turtleCombat** [comment]
I will try and let you know

**Comment by turtleCombat** [comment]
@wxxsw I've done a few tries and as far as I understand it is downloading the entire file? Isn't it possible to limit this? For example, download the first half

**Comment by wxxsw** [comment]
Have you tried setting preloadByteCount to limit preloading?

**Comment by turtleCombat** [comment]
Yes but the problem is not that. The problem is where I set with from. However, it downloads from the beginning to the end.

**Comment by wxxsw** [comment]
Sorry, my English is not very good, and there may be errors in understanding.

- First, this is preload other in the 3 minute:
```swift
playerView.play(for: firstUrl)
playerView.addBoundaryTimeObserver(forTimes: [CMTime(seconds: Double(60 * 3), preferredTimescale: 1)]) {
    VideoPreloadManager.shared.set(waiting: [otherUrl1, otherUrl2])
}
```


- Second, if you just want to play other videos without any delay, you can do this:
```swift
playerView.play(for: firstUrl)
VideoPreloadManager.shared.set(waiting: [otherUrl1, otherUrl2])
```
Don't worry about affecting the playback of the first video, because GSPlayer will stop preloading when the first video buffer is not enough, and start preloading when the buffer is greater than 3 seconds. During playback, this preload state may switch frequently.


- Third, preload other videos, but only the content after the third minute of the video. I thought you needed this, but due to poor English, it should be my mistake understanding.

**Comment by wxxsw** [comment]
Fourth, if you want the first video to be buffered to the third minute, then load other videos. It is not supported now, the current preload logic is completely based on the `Second`.

**Comment by turtleCombat** [comment]
I am not still manage to do that. Actually, if I start at a certain part of the video and download it, it's enough for me to do that. For example I have video 20 mins and I want to download it from 10 mins to end of the video that's all is that possible?

**Comment by yunustek** [comment]
Hi, I'm looking for a way to do this too. Did you find a solution?

**Comment by wxxsw** [comment]
Is this what you want? If so, you can try it.

Podfile:
`pod 'GSPlayer', :git => 'https://github.com/wxxsw/GSPlayer', :branch => 'issue_18'`

Preload:
```swift
VideoPreloadManager.shared.preloadByteFrom = fromByteSize // Now, you need to calculate the result based on the total byte size and duration of the video.
VideoPreloadManager.shared.preloadByteCount = byteCount // It should be possible to set a relatively large number to reach the end of the video.
VideoPreloadManager.shared.set(waiting: [videoURL])
```

**Comment by yunustek** [comment]
Yes thank you I want it. I was try that but downloaded video is not playing when I changed preloadByteFrom to different from 0!

**Comment by wxxsw** [comment]
Actually I don't understand why you want to skip the beginning and preload the second half.

Because the video starts from scratch (even if you seek to the middle immediately after you start it), and the video starts with meta information that might not work without it.

**Comment by yunustek** [comment]
I'm presenting a video that users can watch only in a certain hour and minute. If they miss their time, they can't watch it backwards, so I find the previous one unnecessary to download the minutes, no one can watch anyway.

You say the video starts with meta information. When I first downloaded 1 minute of the video and then tried to download after the 20 minute of the 50 minute video, I couldn't open the video. How much do you think we should download? Or should he get down completely before? Do you have any idea how to fix this problem?

**Comment by wxxsw** [comment]
It sounds a lot like live streaming. If you don't use preloading, it won't meet your needs, right?

**Comment by wxxsw** [comment]
I also want to know how you use it, such as the steps the code executes. (I need to know how to debug it)

**Comment by wxxsw** [comment]
If you have a Demo, you can also upload it to Github and send me a link. If I can reproduce it, I'll try to fix it (if not require major changes).

**Comment by wxxsw** [comment]
Of course, downloading the full video, while not perfect, is a solution.

**Comment by yunustek** [comment]
I haven't tried it in a test project, I have tested it in my own project, but the test is very simple.

Preload a video by starting from a size other than 0 and find the folder where the file was cached and watch the cached video. You will see that the video can be opened only when restarted from 0

**Comment by wxxsw** [comment]
This is my debugging code, if the network is normal, the video file can play.
```swift
let url = URL(string: "http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4")!

VideoPreloadManager.shared.preloadByteFrom = 0
VideoPreloadManager.shared.preloadByteCount = 1024 * 1024
VideoPreloadManager.shared.set(waiting: [url])

DispatchQueue.main.asyncAfter(deadline: .now() + 20) {
    VideoPreloadManager.shared.preloadByteFrom = 1024 * 1024 * 2
    VideoPreloadManager.shared.preloadByteCount = 1024 * 1024 * 30
    VideoPreloadManager.shared.set(waiting: [url])
}

print(VideoCacheManager.cachedFilePath(for: url))
```
