### ISSUE TITLE
Playback continous stalling

### ISSUE THREAD

**Issue by wasimi** [wxxsw/GSPlayer#19]
Trying to load a video with high bitrate (more than 2MB/s), playback keeps getting stalled.

{
  "transportType" : "HTTP Progressive Download",
  "mediaType" : "HTTP Progressive Download",
  "BundleID" : "GSPlayer_Example",
  "name" : "MEDIA_PLAYBACK_STALL",
  "interfaceType" : "Other"
}

Any assistance would be much appreciated.

**Comment by wxxsw** [comment]
Can you provide a high bitrate video URL?

**Comment by wasimi** [comment]
> Can you provide a high bitrate video URL?

Sorry I cant provide the direct url to the resource as its a private bucket and link keeps expiring, but I am sharing this video in particular that would otherwise load properly without any downloading session. 

https://www.dropbox.com/s/gpgi3eo51ybeqg5/IMG_0526.mp4?dl=1

**Comment by wxxsw** [comment]
1. Download to the local, and then play no problem.
2. Using the dropbox online address can not play, it seems that dropbox does not support online play.
3. I started a local service, and then used the downloaded video to test it, and it can actually be played.

So I think it may have nothing to do with the bit rate of the video.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/921863/104012958-b291dc00-51eb-11eb-9fff-ee647bac59e2.png">

**Comment by wasimi** [comment]
Im sorry I forgot to mention that Im loading the video in a Feed style (as your test is portraying Basic style)
Its still happening for us, it may have to do with other videos being downloaded in queue and using a lot of internet bandwidth, since the stall usually occurs in the middle of the Feed.  
1. Does the downloading of a video stop if move to next video to free up resources?
2. In your test while playing locally was the video being cached as well? (Request you to load it Feed style with 5-6 duplicated clips.)
Tried to tweak the bufferSize to 4MB, this seems to start playback w/o stall after a bit of delay but the then it stalls around the middle of the video.
Thanks.

**Comment by wxxsw** [comment]
For example, in UITableView, your video cells are usually reused, so each time you call play(url:) it automatically cancels the previous play and load.

There are no stalls in playing videos from the local service in the Feed, maybe the problem is just network bandwidth?

It is recommended to compress oversized videos to provide a smooth experience.

**Comment by wasimi** [comment]
Thanks for your response, we understand that compression will improve the experience. Its already a great API, looking forward to more improvements and support for hls cache.
Just one more request for you to look into:  I noticed while scrolling downward from current cell, the next cell would display the previous cell for a fraction of a second (I noticed this after removing isHidden on prepareForReuse since we are intending for smoother experience.)
Thanks.

**Comment by wxxsw** [comment]
Each cell should display its own content, but when a cell is reused, the player needs to wait for the scrolling to stop before triggering the playback, so hiding the `playerView` in the `prepareForReuse` (because it is displaying the reused content) is required.

If you want to make it look like there's a player there, you can put a cover image view underneath the player that the player will overwrite when it's playing, but will serve as a preview of the video content when it's not playing.

**Comment by wasimi** [comment]
We thought of showing preview until playback begins. Thanks for the advice though. 
The high res video that I shared does stall on our Android app as well but at least the playback does't stop and continues to play from where it stalls. Not sure how the framework takes care of that.
How does your code handle stalling, even if it's expected to be rare?
Thanks.

**Comment by wxxsw** [comment]
It may be because an error has occurred, you can use `VideoLoadManager.shared.reportError = { error in ...}` to monitor the error and make a judgment.

**Comment by wasimi** [comment]
Hello again, 
This is what happens when we load a video that is high on bitrate (so its size is large). The sdk keeps requesting for very small bytes of data continuously that the player is unable to play, and only until it reaches the end is when the download completes. Can you make anything of it?
What Im asking is the problem is with server config or the SDK unable to request the appropriate offset and length?
Thanks again.
[requests.zip](https://github.com/wxxsw/GSPlayer/files/5857256/requests.zip)

**Comment by wxxsw** [comment]
GSPlayer downloads videos in segments, controlled by offset and length, and played during downloading, which depends on:

1. Put the moov atom in the video on the front
2. The backend supports Accept-Ranges: bytes and Content-Range
