### ISSUE TITLE
Can you set the amount of cache?

### ISSUE THREAD

**Issue by waterdrake** [wxxsw/GSPlayer#20]
Can you set the amount of cache for videos? Or is it unlimited until you clear it?

If there is a set amount of cache, how big is it?

**Comment by wxxsw** [comment]
Get the total size of the video cache.

`VideoCacheManager.calculateCachedSize()`

Clean up all caches.

`VideoCacheManager.cleanAllCache()`

The cache will be stored in NSTemporaryDirectory(), so even if you don't clean it, the system will clean it up.

**Comment by waterdrake** [comment]
Thanks
