### ISSUE TITLE
Random crash while streaming video

### ISSUE THREAD

**Issue by sachinkesiraju** [wxxsw/GSPlayer#21]
I've been getting this exc_bad_access crash repeatedly now both while my video is playing and while the video is seeking.

![Screen Shot 2021-01-30 at 3 36 24 AM](https://user-images.githubusercontent.com/7436977/106355396-63037500-62ac-11eb-996c-2d35bae431dd.png)

If it helps, these are relatively large mp4 files (500MB+) that I'm streaming. Let me know if there's any more info I can get you.

**Comment by wxxsw** [comment]
If possible, send the URL of the video that caused the crash to my email: i@gesen.me
