### ISSUE TITLE
preload for m3u8 video file.

### ISSUE THREAD

**Issue by jitesh-sharma** [wxxsw/GSPlayer#22]
@wxxsw Could you please suggest how to preload m3u8 files too like mp4. I need to implement preload and prefetch functionality for m3u8 files like Instagram does in the reels section. Any idea how we can play videos in the next cell scroll without showing buffer loader.
Like Instagram, We want to prefetch some % of all videos and remaining at the time of video playing

**Comment by wxxsw** [comment]
https://stackoverflow.com/questions/15473493/how-to-download-hls-m3u8-chunks-in-ios-device

**Comment by jitesh-sharma** [comment]
The above link is not working as expected or as your library is doing for mp4 format. Don't you think the Mp4 video is heavy as compared to the m3u8? Your library is doing awesome work for mp4 but when bandwidth/internet connection is very slow. m3u8 would be a much better solution as compared to mp4. You can add the same functionality for m3u8 as a new feature.

**Comment by wxxsw** [comment]
While M3U8 is a fine format, the way to support playback while downloading is completely different from MP4.

MP4 uses AVassetResourceLoader, but M3U8 uses HTTP Server.

But I will consider supporting it in the future, when I have time to do it.

**Comment by GuriSarao** [comment]
@wxxsw thanks for your quick revert so will you do it in future :)
