### ISSUE TITLE
video play pause issue in collection view cell 

### ISSUE THREAD

**Issue by MaazSiddique** [wxxsw/GSPlayer#24]
I am trying to pause and play on click of collectionView cell.. I am trying to instant pause and instant play the video. but it ends with error or it doesn't work that fast..

**Comment by wxxsw** [comment]
Can you provide code, error message, recording screen, etc

**Comment by MaazSiddique** [comment]
> Can you provide code, error message, recording screen, etc

please send me your email, I will send you

**Comment by wxxsw** [comment]
i@gesen.me
