### ISSUE TITLE
Video stuck when the internet speeds slow At that time I need to display buffer loader so please help me how to set loader when the video goes to buffer.

### ISSUE THREAD

**Issue by barotbhavesh** [wxxsw/GSPlayer#25]
@barotbhavesh 
```swift
playerView.stateDidChanged = { [weak self] state in
    guard let self = self else { return }
    
    if case .paused = state, self.playerView.pausedReason == .waitingKeepUp {
        // buffering
    }
}
```

_Originally posted by @wxxsw in https://github.com/wxxsw/GSPlayer/issues/13#issuecomment-768088963_

I am trying the given solution but when the video goes to buffer at that time "state" I am getting ".playing" and I am adding the condition on 

 case .playing:
 if case .paused = state, self.playerView?.pausedReason == .waitingKeepUp {
 self.activityIndicator.startAnimating()
} else if case .playing = state, self.playerView?.pausedReason == .waitingKeepUp {
 self.activityIndicator.startAnimating()
 } else {
self.activityIndicator.stopAnimating()
}

and one more thing I am also getting "self.playerView?.pausedReason == .waitingKeepUp" when video playing

**Comment by barotbhavesh** [comment]
Hello @wxxsw any update for me because I need to fix this issue as soon as possible.

**Comment by wxxsw** [comment]
1. Because PausedReason relates only to a paused state, the playing state should not use PausedReason.
2. Theoretically, if the video is stuck, it should be paused or loading instead of playing. However, I did not reproduce it.

**Comment by barotbhavesh** [comment]
@wxxsw I am also getting 
self.playerView?.pausedReason == .waitingKeepUp
When state is **case .playing:**

so how can I check the condition if video come from buffering in **.playing**.

**Comment by wxxsw** [comment]
Actually the question is why does the video stop but the state is **.playing**.

**Comment by barotbhavesh** [comment]
@wxxsw because video goes to buffer and at that time state is **.playing**
if you check with a low internet connection at that time you face this issue.
can you please check with mobile data ( ON 3G)

**Comment by wxxsw** [comment]
Understand, I have time to solve this problem on weekends.

**Comment by barotbhavesh** [comment]
@wxxsw thank you

**Comment by barotbhavesh** [comment]
@wxxsw 
when I pause the video with **.paused state**
at that time i am getting **self.playerView?.isMuted **false****

**Comment by wxxsw** [comment]
isMuted only indicates whether it is muted or not, and will not change because there is no sound after the pause
