### ISSUE TITLE
next and previous button

### ISSUE THREAD

**Issue by M0TRIX** [wxxsw/GSPlayer#29]
hello.

I added Next and Previous buttons for playing multiple videos but there is a problem with changing video

```
 @IBAction func nextAction(_ sender: Any) {

        playerView.play(for: URL(string: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4")!) // next video's url
    }
```

this is the way I'm changing the videos //

**Comment by wxxsw** [comment]
Please describe your problem in more detail, and the Feed Demo also shows how to switch videos
