### ISSUE TITLE
Callback when video ends

### ISSUE THREAD

**Issue by mukesh1430** [wxxsw/GSPlayer#3]
How to get callback when video ends?

**Comment by yunustek** [comment]
@wxxsw  Why playToEndTime always trigged. It need trigger when audio ending.

**Comment by wxxsw** [comment]
@yunustek 
I added the following code to the demo BasicViewController.swift viewDidLoad(), and did not find any repeated calls.
```swift
playerView.playToEndTime = {
    print("playToEndTime")
} 
```

**Comment by yunustek** [comment]
I don't know why but it triggered all time. It is constantly triggered before and after the play progress is over.
![image](https://user-images.githubusercontent.com/9871990/107970640-6ee87a00-6fc2-11eb-9510-481d63e21ec4.png)

**Comment by wxxsw** [comment]
@yunustek I tried to fix it and released version 0.2.22, you can see if the problem is solved.

**Comment by yunustek** [comment]
@wxxsw my current version is 0.2.17 sorry I now see your other releases. I will upgrade to 0.2.22 and test it

**Comment by yunustek** [comment]
There is also a problem like this, after the game is over, it still continues to enter playToEndTime. To stop this, you also need to remove the NotificationCenter observer, I think you were able to look at it?

**Comment by yunustek** [comment]
@wxxsw my current version is 0.2.17 sorry I cant upgrade to 0.2.22. but I can upgrade to 0.2.20 why?

**Comment by yunustek** [comment]
@wxxsw by the way I was try playToEndTime is trigged only after video finished but It is triggered more than 1 times, keeps triggering even though I turn off the screen

**Comment by wxxsw** [comment]
Version 0.2.23 added:
```swift
deinit {
    NotificationCenter.default.removeObserver(self)
}
```

**Comment by wxxsw** [comment]
Does your view controller call deinit?

**Comment by yunustek** [comment]
Yes it's calling deinit. And I can't see the viewController on memory hierarchy but videoPlayer is still working
I will try new version
