### ISSUE TITLE
Video buffer playing issue

### ISSUE THREAD

**Issue by barotbhavesh** [wxxsw/GSPlayer#35]
Is any way to play buffer video just an Example 
My video goes to buffer at that time video stuck and buffer time is increase 55% ..56%..60%...and 100%. After 100% video play with start. 
I need to when the video goes to buffer like 55% and then buffer time going to 75% in between 55% to 75% **VIDEO WANTS TO PLAY BUT IN** current scenario video not play.

can you please help me with how to handle this issue?

**Comment by wxxsw** [comment]
It may not be easy, because whether to play is controlled by AVPlayer.

Maybe you can try to check the buffer frequently and call resume manually, but I'm not sure if this is useful.
