### ISSUE TITLE
Audio keeps playing  after closing controller

### ISSUE THREAD

**Issue by ajeetpratap** [wxxsw/GSPlayer#36]
I have a controller with collectionCell. Everything works fine but when I pop the controller when the video is playing the audio doesn't stop.
Is there any global setting which I can set that will make my AVPlayer stop playing the audio?

**Comment by Hemrajjhariya** [comment]
facing same problem .

**Comment by 8secz-johndpope** [comment]
In the deinit of the cell 
You will want / need to tear down appropriately

**Comment by wxxsw** [comment]
> In the deinit of the cell
> You will want / need to tear down appropriately

Yes, you need to stop the player manually before leaving the interface.
