### ISSUE TITLE
expose helper to cancel download

### ISSUE THREAD

**Issue by 8secz-johndpope** [wxxsw/GSPlayer#38]
```swift
    override func prepareForReuse() {

        super.prepareForReuse()

  playerView.player?.currentItem?.asset.cancelLoading()

}
```

should be just
`  playerView.cancelLoading()`

or did I miss something?

<img width="1464" alt="Screen Shot 2021-04-02 at 9 45 14 pm" src="https://user-images.githubusercontent.com/50567111/113409306-ba34db80-93fc-11eb-9199-90ce5bfca9d6.png">

**Comment by wxxsw** [comment]
I have changed to public
