### ISSUE TITLE
Can not play video from googlevideo.com

### ISSUE THREAD

**Issue by vuongdangvu** [wxxsw/GSPlayer#5]
https://r3---sn-i3b7knsl.googlevideo.com/videoplayback?expire=1593620297&ei=6WL8Xp3HJMqS4QK4q4F4&ip=27.72.96.161&id=o-ACw9N4uUIDd3MrcNzsRPb9fcEXmyFfwQFD5j0e-aFk-d&itag=18&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&gir=yes&clen=16297211&ratebypass=yes&dur=210.976&lmt=1550048317876301&fvip=3&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKt9DZBRWot9pAKGl4YUwTOsQcF9RBuqXKQPThW7Cm8GAiBJcamPznbTCUEtQfpmlW_mZBHL0m5UktYBy_7HNpumbg%3D%3D&redirect_counter=1&rm=sn-8pxuuxa-i5ozz7s&req_id=c42147d9f0b2a3ee&cms_redirect=yes&ipbypass=yes&mh=q0&mm=30&mn=sn-i3b7knsl&ms=nxu&mt=1593598640&mv=m&mvi=2&pl=20&lsparams=ipbypass,mh,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRAIgKW3tYK3X3g-PlLkeAKaVhmPkwF6Xb71VD38jit-23q8CIA7x41AM8BieGH8PmPQ-9l-5IQg1V1VMU9CfhyYrna4F

i use this video but video not show .

**Comment by wxxsw** [comment]
I can't open this link with my browser, and it shows http 403 error

**Comment by vuongdangvu** [comment]
maybe link above is expired . i have been try another link but it not play

**Comment by wxxsw** [comment]
I debugged it and the error was mainly caused when the resourceloader downloaded the file to AVPlayer for playback. I’m not sure about the specific reason for the time being, but I hope you can test the file with extension in the URL, such as https://.../videoplayback.mp4

**Comment by vuongdangvu** [comment]
Thanks for replied.. but i need support more format .. i also use AvPlayer and can play all  but i facing with high memory

**Comment by wxxsw** [comment]
Ok, actually GSPlayer is completely designed for mp4 and used in the projects I work on, so it has limitations, but for me it works very well.

**Comment by vuongdangvu** [comment]
Ok thanks for support : D

**Comment by wxxsw** [comment]
Sure, no problem :D
