### ISSUE TITLE
Is it possible to add http request header?

### ISSUE THREAD

**Issue by ggua5470** [wxxsw/GSPlayer#52]
Is it possible to add http request header? E.g.  adding a header for "Referer".
Sometimes we need to check the referer to limit hot links.

This feature is quite commonly seen in other library like Alamofire.

Thanks

**Comment by wxxsw** [comment]
VideoLoadManager.shared.customHTTPHeaderFields = { url in
    if (url == ...) {
        // do something
    }
    return [:]
}

**Comment by ggua5470** [comment]
Oh great!
I searched "http" or "header", but Github returns no results..
