### ISSUE TITLE
Method cannot be in an @objc extension of a class (without @nonobjc) because the type of the parameter 1 cannot be represented in Objective-C

### ISSUE THREAD

**Issue by junkwei** [wxxsw/GSPlayer#8]
![image](https://user-images.githubusercontent.com/12404249/93425591-e4093380-f8ec-11ea-8609-a47b6024b6b1.png)

**Comment by junkwei** [comment]
![image](https://user-images.githubusercontent.com/12404249/93425707-1f0b6700-f8ed-11ea-988c-dc5416c8b982.png)

**Comment by junkwei** [comment]
以上问题出现在升级Xcode 12.0后，跑模拟器14.0的时候出现

**Comment by junkwei** [comment]
![image](https://user-images.githubusercontent.com/12404249/93426372-78c06100-f8ee-11ea-914f-41c48317d2fd.png)

**Comment by junkwei** [comment]
![image](https://user-images.githubusercontent.com/12404249/93426420-97bef300-f8ee-11ea-95ce-bae63ea27f32.png)

**Comment by junkwei** [comment]
以上问题出现在升级Xcode 12.0后，跑模拟器14.0的时候出现

**Comment by molchanovskiy** [comment]
same here, xcode 12

**Comment by wxxsw** [comment]
It has been fixed, please update to the latest version 0.2.17
