### ISSUE TITLE
Caching doesn't work on iOS 17

### ISSUE THREAD

**Issue by waterdrake** [wxxsw/GSPlayer#85]
Video caching doesn't seem to work on iOS 17 anymore. I didn't change anything with my code, but only updated the phone version and it won't cache at all.

Anyone else having the same issue?

EDIT: Or maybe the cache is full, so no more videos will be cached? Is there any limit to the cache?

Should we be clearing the cache with VideoCacheManager.cleanAllCache() so that new videos will be cached?

**Comment by vkhadyka** [comment]
I'm experiencing the same difficulties.
I did debug and realized that iOS 16 and  iOS 17 has different behavior for one condition.

I've added 
```
print((AVPlayerItem.loaderPrefix + url.absoluteString + ".mp4").url)
print(AVPlayerItem.loaderPrefix + url.absoluteString + ".mp4")
```
before this line
`guard let loaderURL = (AVPlayerItem.loaderPrefix + url.absoluteString + ".mp4").url else {`
[full path](https://github.com/wxxsw/GSPlayer/blob/706fc28fcc8e33607993903eca82d9f6c7c3f6d2/GSPlayer/Classes/Extension/AVPlayerItem%2BExtensions.swift#L64)
and get different output 

iOS16 output: 

> Optional(__loader__http://vfx.mtime.cn/Video/2019/06/29/mp4/190629004821240734.mp4.mp4)
> __loader__http://vfx.mtime.cn/Video/2019/06/29/mp4/190629004821240734.mp4.mp4

iOS17 output: 

> nil
> __loader__http://vfx.mtime.cn/Video/2019/06/29/mp4/190629004821240734.mp4.mp4

**Comment by gbuela** [comment]
Just changing `AVPlayerItem.loaderPrefix` to something else without the underscores seems to work.
I will try to submit a PR.

**Comment by gbuela** [comment]
Here: https://github.com/wxxsw/GSPlayer/pull/89
