### ISSUE TITLE
After paused how to play video from first frame with 0 replay count and 0 watch duration?

### ISSUE THREAD

**Issue by sandeep-yudiz** [wxxsw/GSPlayer#9]
**Step 1** Play Video 1 
**Step 2** Paused Video 1
**Step 3** Play video 2
**Step 4** Paused _Video 2_ and play _Video 1_ with zero **seek** with **zero repeats** count and **zero watch duration**.

**Current behaviors** Right now Step 4 on **Video 1**  play with last **paused duration onward** with watch duration and repeat count.

**We need how to play the video1 with zero seek with zero repeat count and zero watch duration**

**Comment by yudiz-vipul** [comment]
@wxxsw Can you please add a method to reset watch duration and play to the first frame?

**Comment by sandeep-yudiz** [comment]
@wxxsw Can you please add a method to reset watch duration and play to the first frame?

**Comment by wxxsw** [comment]
Ok i will take a look now

**Comment by wxxsw** [comment]
I set replayCount as a settable property, what do you think?

**Comment by wxxsw** [comment]
Adding a reset method is also good, let me add it.

**Comment by wxxsw** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/921863/97280601-72bb8980-1877-11eb-9cd9-0c60151fc45e.png">

**Comment by wxxsw** [comment]
Added replay method:

When the parameter value is false, return to the beginning of the video and increase replayCount.
When the parameter value is true, return to the beginning of the video and reset the replayCount.

**Comment by wxxsw** [comment]
Submitted a new pod version 0.2.18.
